[package]
name = "blog"
version = "0.1.0"
authors = ["fdeĉ <fd@42l.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
askama = "0.11.1"
actix-files = "0.6"